emsdk

With reference to - https://github.com/kripken/emscripten/issues/3267

Adding error checking on install

---

emsdk_manifest.json

This is to resolve kripken/emscripten#3601

Fixing tag - omitted one character

---

README.md

Hi! Thanks for Emscripten. This pull-req correct some grammatical errors in the README. Please consider merging it.

Correct some grammar errors in the README.

---

README.md

In the README.md. Please pull.

Correct some phrasing/grammar/etc. problems.

---

emsdk

treat Cygwin enviroment as Linux.

Add Cygwin Support

---

emsdk
emsdk.bat
emsdk.ps1
emsdk_env.ps1

Support PowerShell environment

---

emsdk.ps1

It should use `./` to access the current directory.
(I added emsdk to the system path so I couldn't catch this. Sorry 😅)

Fix powershell env directory

---

emsdk
emsdk_manifest.json

Support for building upstream LLVM from source

---

emsdk_manifest.json

Fixes https://github.com/juj/emsdk/issues/148

There is no binaryen-incoming, point incoming sdks at binaryen-master

---

Dockerfile
emsdk

Also attempt to add both python2 and 3 testing on CI here.
Fixes #240.

Fix emsdk on python3 - the values() of a dict is a view there, not a list

---

Dockerfile
test.sh

Move testing into a bash file on the side

---

.gitignore

Exclude `fastcomp` and `releases`

---

emsdk

[windows] Replace python2-specific error handling with a string check that works in python3 as well

---

emsdk.ps1

Fix powershell file association after emsdk script rename

---

emsdk_manifest.json

Original change that got reverted: #331
See https://github.com/emscripten-core/emscripten/issues/9332

reland: Update default node version to 10.16.3

---

.flake8
emsdk.py
test.py

- Remove some unneeded use of `global` keyword
- Use OrderedDict
- Add exit_with_error helper
- Remove SPIDERMONKY_ENGINE from emscripten config

Cleanup emsdk.py

---

emsdk.py
emsdk_env.csh

This is a different approach, superseding #363, after the comments made by @sbc100 there.

Add support for constructing a t?csh environment

---

emsdk.py

Delete the old EMSDK_DEV option that is no longer used.

Remove unused EMSDK_DEV option.

---

emscripten-releases-tags.txt

I suppose this was just forgotten?

Update the latest release tag

---

emsdk.py

Currently, the installation of emscripten fails when the emsdk.py file is run under any of the MinGW versions of Python:
```
logic@LAPTOP-0OF3O041 MINGW64 ~/emsdk
$ ./emsdk install latest
** NOTICE **: The default SDK changed from `fastcomp` to `upstream`.
If you have problems, or wish to revert back to fastcomp for some other reason
you can add `-fastcomp` to explicitly install that fastcomp-based
SDK, .e.g ./emsdk install latest-fastcomp.
Installing SDK 'sdk-releases-upstream-b3ddcab6efd749d3ed937fb452ace4e39a825842-64bit'..
Installing tool 'releases-upstream-b3ddcab6efd749d3ed937fb452ace4e39a825842-64bit'..
Downloading: C:/msys64/home/logic/emsdk/zips/b3ddcab6efd749d3ed937fb452ace4e39a825842-wasm-binaries.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win …
```

Fix issue with Windows paths under MinGW versions of Python

---

README.md
emsdk.py
emsdk_manifest.json

See https://github.com/emscripten-core/emscripten/issues/10067

Remove use of incoming branches

---

emsdk.py

Fixes https://github.com/emscripten-core/emscripten/issues/10246

Pass `--no-audit` to `npm install`

---

emsdk.py

This change simply splits this function into its two logical parts.

Extract `install_sdk` and `install_tool` from `install`. NFC

---

emsdk.py

Meant to resolve https://github.com/emscripten-core/emsdk/issues/412#issuecomment-566501047

Fix ZIP extraction on Windows.

---

README.md

I did a skim on the README and attempted to fix some of them. I may have seen some oversights but I'll update when able.

Fix some grammar errors in README

---

emsdk_manifest.json

Add pywin32 to windows python installation

---

emsdk.py

Refactor such that Tool.activated_config returns a map. NFC

---

.circleci/config.yml

We only publish on tag, but we want to build and test the image
on all PRs.
See #526

Build docker image as part of CI

---

docker/Dockerfile

As requested by @curiousdannii in https://github.com/trzecieu/emscripten-docker/issues/58#issuecomment-648760800

Add standard workdir for Dockerimage

---

emsdk.py

Fix running emsdk_env.sh outside of emsdk directory

---

emsdk.py
emsdk_manifest.json

I think that is what they want us to call it these days.

Rename osx -> macos

---

emsdk.ps1

This makes it fail when run from a project directory.
Thansks @sbc100 for finding the problem :)

[powershell] fix emsdk.ps1 assuming emsdk_set_env.ps1 lives in PWD

---

emsdk.py

Its particularly important during `construct_env` where stdout
is directly interpreted by the shell.
See: #385

Log warnings to stderr

---

emsdk_env.sh

Closes emscripten-core/emscripten#6743

Make emsdk_env.sh work under set -o nounset

---

emsdk
emsdk.bat
emsdk.py
scripts/test.py

Clear PYTHONHOME when using bundled python

---

emsdk.py

fix sln parsing form vs2019

---

emsdk.py

Also, make handling of activated_path consistent.  We don't support
multiple activated paths so we can simplify the handling in some
places.

Remove unused run_emcc function. NFC.

---

emsdk.py

Without this, all releases are made available as fastcomp
versions.
Also, sort the releases to that the most recent come last.
This fixes the `emsdk list` display which only displays
the two most recent versions.

Limit expansion of %releases-tag% for fastcomp

---

.dockerignore
emsdk.py

Remove unneeded try/catch

---

scripts/test.py

This change should not effect the actual test coverage, it just refactors code into methods
on a TestCase class.

Refactor test.py to use python unittest. NFC.

---

emsdk.py

Since #732 we lookup tot release dynamically, but we don't
necessarily want to do this for the `activate` command otherwise
`install` followed by `activate` a can fail if a new build was
produced inbetween.

Fix race between `install tot` and `active tot`

---

bazel/emscripten_toolchain/wasm_binary.py

Remove absl from wasm_binary

---

README.md
emsdk.bat
emsdk.ps1
emsdk_manifest.json
scripts/update_python.py

Update to python 3.9.2 on Windows as well. Mark old Python and Node packages.

Update to python 3.9.2 on Windows

---

emsdk.py

Fix issues with npm install of google-closure-compiler installing all (unwanted) dev packages as well.

Fix issue with npm install installing dev packages

---

README.md

Switch primary branch from `master` to `main`

---

emsdk.py

Add warning to those using `master` branch

---

emsdk.py

This file in in the repo itself contains a newline so we should match
that.  Also everybody knows that text files should end in a newline :)

Add newline at end of emscripten-version.txt

---

emsdk.py

Fixes: https://github.com/emscripten-core/emscripten/issues/14446

Point zsh and csh users to the correct startup script

---

emsdk.py

See https://github.com/emscripten-core/emscripten/pull/15144

Fix emscripten-version parsing

---

emsdk.py
test/test.py

Followup to #930: Add a tests, and remove newly-unused arguments
to unzip and untargz.

Add test and remove unused args

---

bazel/emscripten_toolchain/emar.sh
bazel/emscripten_toolchain/emcc.sh
bazel/emscripten_toolchain/emcc_link.sh
bazel/emscripten_toolchain/env.sh

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

Fix building rules_foreign_cc targets in Bazel.

---

bazel/BUILD

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

Allow @emsdk to be imported in a non-x86_64 host.

---

emsdk_manifest.json
scripts/update_python.py

Fixes: https://github.com/emscripten-core/emscripten/issues/16073

Rebuild MacOS python with lzma module installed

---

emsdk_manifest.json
scripts/update_python.py

Fix mac python by avoiding linking libintl

---

emsdk.py
test/test.py

Also, add tests for unknown architecture and wrong bitness and
add a mechanism (`EMSDK_ARCH`) to override the architecture assumed
by emsdk.

Error (don't just warn) on unknown architecture

---

bazel/emscripten_toolchain/wasm_cc_binary.bzl

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

Provide "executable" in wasm_cc_binary's DefaultInfo.

---

emsdk.bat

Update emsdk.bat after recent python update

---

emsdk.py

When doing a git clone of a branch, instead of doing a general git clone that first would check out the default (main/master) branch and then later doing a checkout to switch to the target branch, instead specify the `--branch` option to the clone command line to immediately clone and checkout the desired final branch.
This helps first checkout runtime performance on CIs, especially when using shallow clones (GIT_CLONE_SHALLOW option).
Also this sidesteps a really odd git clone issue we are currently seeing in our CI, where it is unable to `checkout` the googletest submodule in binaryen, but would fail saying "path not found".

Git clone desired target branch directly

---

bazel/emscripten_deps.bzl

Also some minor formatting fixes.
This fixes the bazel build.

include node modules glob with linker files. 

---

emscripten-releases-tags.json
emsdk.py

Pin `latest` to a specific version for arm64-linux

---

.circleci/config.yml

Update XCode version on CircleCI

---

.circleci/config.yml

20.10.17 is the current default.

Update remote_docker version in CircleCI config

---

bazel/deps.bzl
bazel/emscripten_toolchain/BUILD.bazel

Refs https://github.com/emscripten-core/emsdk/issues/1020

Upgrade to rules_nodejs 5.8.0

---

emsdk.py

These function ever return strings

Remove uneeded str. NFC

---

emscripten-releases-tags.json

Update arm64 linux release

---

.circleci/config.yml

See https://github.com/emscripten-core/emscripten/pull/21110

[ci] Update to latest version of cicleci windows orb

---

bazel/README.md

Provides simpler using and less errors

[bazel] Update README.md

---

bazel/README.md

Edit some version variables to make correct installation and  text under.

[bazel] Fix some inaccuracies NFC

---

.github/workflows/tag-release.yml

Rename secret from test to production name

Switch token name in release action

---

README.md

Minor addition to bring README.md in line with the web documentation. Resolves #1447.

Add git pull to README.md

---

scripts/update_node.py
scripts/update_python.py
scripts/zip.py

This way update_node.py can be called on Windows host machines as well.

Use zip_cmd() and unzip_cmd() in update_node.py as well.

---

.github/workflows/create-release.yml

This allows filtering PRs to more easily find releases.

Add "release" label to PRs created for releases

---

.circleci/config.yml
.flake8

https://pypi.org/project/flake8
```diff
-     - run: python3 -m pip install flake8==3.9.2
+     - run: python3 -m pip install flake8==7.1.1
```

Python lint: Upgrade to flake8=7.1.1

---

.circleci/config.yml
bazel/.bazelrc
test/test_bazel.sh

This is a temporary fix until I can do https://bazel.build/external/migration

Fix bazel ci

---

bazel/deps.bzl
bazel/emscripten_deps.bzl

hopefully this unblocks the release?

Update node for bazel

---

scripts/update_bazel_workspace.py

The regex was not matching which caused #1549 to fail.

Fix updating of MODULE.bazel in update_bazel_workspace.py

---

scripts/update_bazel_workspace.py

Use raw string to avoid regex warning
