emscripten-core/emsdk

emsdk

The `python` binary invoked by `emsdk` might be Python 3. But the script isn't ready to run under Python 3. With these changes, I at least managed to get a setup installed and activated using Python 3, so it looks good even though I can't guarantee that I got the unicode versus bytes distinction correct in all places. Python 2.7 should be fine as well. And I doubt we should care too much for Python versions older than that.
Compare kripken/emscripten#792 about Python 3 support in emscripten itself.

Python3 support

---

emsdk

Branch names may contain path separator characters like '/', especially under git-flow.
emsdk fails to build when path separators are contained.
I fixed it with replacing path separators to '-'.

Allow path separator characters in branch names

---

emsdk_env.sh

$_ is "The last argument of the previous command." (cf. man zshparam) on zsh, so SRC will be "]".

Use $0 to get execution path

---

emsdk

I'd like to copy the emsdk directory around freely. The --embedded option almost does the job but it still leaves absolute paths in the .emscripten config file. This change will make all absolute paths derived from the location of the .emscripten file itself. I tested this briefly for my setup and it seems to work. Could you please merge this?

Make .emscripten config file relocatable when using the --embedded flag

---

emsdk_env.bat

Previously user needs to switch current directory to the location of `emsdk_env.bat`, call it, then switch back to previous directory to continue his works.

Call emsdk_env.bat without changing curr dir

---

emsdk

Recent versions of `sdk-incoming` have WebAssembly support, but there was no way in `emsdk` to build LLVM with support for native Wasm generation (instead of Asm.js to Wasm conversion). 
This commit adds a flag `--enable-wasm` to the `emsdk` tool to enable that in turn adds `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly` when building LLVM. This should allow adventurers to try this feature using their beloved `emsdk` without needing to compile LLVM manually.

Add option to enable WebAssembly in LLVM

---

emsdk

It seems github requires a specific URL format for reaching repos. `emsdk update-tags` will randomly fail when the convention is not followed.

Fix random errors fetching from github

---

emsdk

In Python 3 `map` BIF returns some kind of a single-pass iterator.
`self.uses` is empty here:
https://github.com/juj/emsdk/blob/4ed531f67929f06ca11fdd22016652363f95c151/emsdk#L1291
so the following won't install anything:
```
$ EMSDK_VERBOSE=true ./emsdk install latest
CMAKE_GENERATOR: Unix Makefiles
Installing SDK 'sdk-1.37.18-64bit'..
Done installing SDK 'sdk-1.37.18-64bit'.
```
The patch has no impact on Python 2 behavior.

Python 3 compatibility - wrap map objects in lists

---

emsdk

`-xvf` is too verbose, use `-v` only when `EMSDK_VERBOSE` is on.

Less verbose unpacking

---

emsdk

When interrupting a download with something like control c the program will quit but won't clean it self up and will leave an invalid file. There is a handler for Exception, but this wont catch interrupts. If you try to rerun the program it won't try to re-download it the next time.

Catch KeyboardInterupt in download_file

---

emsdk_manifest.json

Current emsdk only provides it for incoming and tagged downloads, it should also provide it for precompiled ones.

Provide Node.js 8 also for precompiled tools

---

emsdk

I did this to list the dependencies on each sdk, so that I can install the packages without interfering with my nodejs environment.  I don't think that this can be used with ```--old``` due to ```sys.argv``` being used directly, instead of using argparse.  I am not sure the formatting is acceptable, but I think it is valuable to gather the info quickly on the command line, instead of digging through the json manifest.

list sdk depends

---

README.md

We no longer have the resources to produce and maintain `emsdk-portable.*`. The emscripten main docs have already been changed to reflect that, but the emsdk repo had links to them. This replaces those links with a link to the main website docs, so we just have a single central location for how to get started with the sdk.

Do not link to emsdk-portable.*, link to the main website docs

---

emsdk_manifest.json

We already include a build of binaryen (as a subdirectory of clang) when fetching prebuilt binaries, but when building from source we don't build binaryen as well. As we move to requiring binaryen be set via BINARYEN_ROOT in the config file (which emsdk already handles writing), we'll always need binaryen built. This should make that easier for users.

Build binaryen from source when building tagged sdk versions from source

---

emsdk

And emscripten doesn't need it anyhow (it's for handwritten js users).
This binaryen change broke tagged version building,
http://ec2-54-213-252-128.us-west-2.compute.amazonaws.com:8112/#/builders/5/builds/193
Hopefully this will fix it, although I'm unsure how the bots receive updates to the emsdk script - @juj, do you know?

binaryen.js is no longer bundled in binaryen

---

.gitignore
emsdk
emsdk_manifest.json
upstream/lkgr.json

This fetches the latest revision of the prebuilt wasm backend off the wasm waterfall (https://wasm-stat.us)
Only tested on linux, and the linux build is the only one that's regularly green at the moment, so that's all that's supported for now.
Going forward I'm not sure what sort of release process we want for mapping emscripten tags with upstream LLVM commits. Some ideas I can think of are:
1) Fork LLVM, create a new branch off of latest master when we tag an emscripten version, with the only diff being the addition of an `emscripten-version.txt`
2) Don't track LLVM commits, but LLVM releases (6.0.0, 5.0.2, etc)
3) Some explicitly managed lookup for the revisions, living either in emsdk or emscripten
4) Include `emscripten-version.txt` in upstream LLVM
I think I like 3) the best but in …

Add upstream waterfall tools and sdk

---

emsdk

This is useful in CI environments that claim to be TTYs but
really don't have escape characters such as \r correctly.

Add --notty to force non-erasing progress bar

---

Dockerfile
emsdk
emsdk_manifest.json

This makes it possible to tell the emsdk to get "latest-upstream", which fetches the latest lkgr from there. This will probably be a common use pattern, I expect we may want to recommend users start trying out the wasm backend that way soon. This will also let us simplify this code: https://github.com/kripken/emscripten/blob/incoming/.circleci/config.yml#L334
Aside from adding the "latest-upstream" alias,  this PR has
* A few minor cleanups in the emsdk code.
* Minor restructuring of how we define the upstream stuff in the manifest: It seemed odd to have 3 things (clang, emscripten, binaryen) that are all coming from a single archive from the waterfall. Simpler to have just one - the archive is one big lump, there's no way to download just part of it.
* Also add node 8.9.1 as a dependency …

Enable "emsdk [install|activate] latest-upstream"

---

.travis.yml

(which was there just from some old copy-paste, I think)

Avoid a Docker warning on an unused build arg

---

Dockerfile
emsdk
emsdk_manifest.json

With this, we can do `emsdk install latest-fastcomp` and it installs fastcomp from the waterfall. That is, we then have 3 main sdks people might want to use:
* `latest` which installs **fastcomp**-llvm (plus emscripten etc.) from the **mozilla** infrastructure. (fetches the last emscripten version there)
* `latest-upstream` which installs **upstream**-llvm (plus emscripten etc.) from the **waterfall** infrastructure. (fetches the last known good revision (lkgr) there)
* `latest-fastcomp` which installs **fastcomp**-llvm (plus emscripten etc.) from the **waterfall** infrastructure. (fetches the last known good revision (lkgr) there)
The first and last are currently somewhat overlapping in that both fetch a build of fastcomp. However, as we transition away from the mozilla infrastructure, …

Add 'latest-fastcomp' sdk

---

Dockerfile
emsdk
emsdk_manifest.json

(This was reverted by mistake. It had a bad commit message though, so relanding with a nicer one is nice anyhow.)
With this, we can do emsdk install latest-fastcomp and it installs fastcomp from the waterfall. That is, we then have 3 main sdks people might want to use:
* latest which installs fastcomp-llvm (plus emscripten etc.) from the mozilla infrastructure. (fetches the last emscripten version there)
* latest-upstream which installs upstream-llvm (plus emscripten etc.) from the waterfall infrastructure. (fetches the last known good revision (lkgr) there)
* latest-fastcomp which installs fastcomp-llvm (plus emscripten etc.) from the waterfall infrastructure. (fetches the last known good revision (lkgr) there)
The first and last are currently somewhat overlapping in that both fetch a …

Re-land #200

---

Dockerfile
emsdk

We removed it in Binaryen #1858. The reference here broke source installs using the emsdk.
Fixes https://github.com/juj/emsdk/issues/206

Remove wasm.js reference

---

emsdk_env.sh

Fixes #219 
I also replaced the backticks with `$()` because they're the modern POSIX standard and look moderately prettier. I'm fine changing it back.

Remove bashism in emsdk_env.sh in favor of portable alternative

---

emsdk
emsdk_manifest.json

Without this, we would not download new versions, as the filename looked the same ("already downloaded"). We'd unzip those old contents to a directory with the new name, giving the impression we updated when we didn't :(

Add the lkgr as a prefix to upstream downloads

---

.travis.yml

In theory this should speed it up a little.  I suppose it was
initially added because we use docker but it doesn't seem that is
requirement here.

Remove sudo from travis configuration

---

emsdk_env.sh

It seems that some variables were mistakenly left unquoted, leading to paths containing spaces being treated incorrectly.
For example, the directory `/home/person/foo bar/test/` would cause `CURDIR=$(pwd)` to be expanded to `CURDIR=/home/person/foo bar/test/`. This means that the shell would attempt to run the command `bar/test/` with the environment variable `CURDIR` set to `/home/person/foo`. This is due to [word splitting](https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html). TL;DR the result of shell expansions should probably be quoted 99% of the time to be extra safe/compatible with spaces. (I say 99% because there are rare exceptions such as `"$@"` and running the contents of a variable)

Fix bug introduced in #220

---

emsdk_env.fish

Fish shell doesn't support the same syntax as most shells,
so add an emsdk_env.fish to support these users.
Instructions included in `emsdk_env.fish`.

Support Fish shell (emsdk_env)

---

emsdk_manifest.json

Add SDK definitions for upstream wasm backend enabled LLVM, "sdk-wasm-master-32/64bit".
With this, one can get going with the upstream wasm backend with
```
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
emsdk install sdk-wasm-master-64bit # Compiles llvm-mirror/llvm master branch from source
emsdk activate sdk-wasm-master-64bit
source ./emsdk_env.sh
cd emscripten/incoming
em++ tests/hello_world.c -o a.js
node a.js # runs a.wasm produced with upstream wasm backend
```
I was a bit surprised we did not have something like this already, what is the workflow that you guys have been using? @kripken @dschuff @jgravelle-google ?
Compare the above with using the traditional fastcomp based backend, which is used with:
```
git clone https://github.com/emscripten-core/emsdk.git
cd …
```

sdk-wasm-master

---

.gitignore
upstream/lkgr.json

It was removed to try to unbreak the old buildbots. That only partially worked, but in any case at this point we are starting to get builds on the new ones, so we don't need that workaround. And restoring it avoids an annoying warning that people are seeing.

Restore lkgr.json

---

Dockerfile
emsdk
emsdk_manifest.json

We can remove this now that we have emscripten-releases working and use it everywhere we used the emsdk's waterfall integration.
In particular this should fix the current lkgr.json errors people are seeing (by removing all the lkgr stuff), which I believe started when I refactored that code while doing the releases work - I must have gotten something wrong on non-linux OSes. But anyhow, easier to remove that unnecessary code than fix it at this point.

Remove waterfall integration

---

emsdk
emsdk_manifest.json

This allows us to always unpack our builds into `upstream/` or `fastcomp/`, instead of creating a new directory each time. Since without this, we'd get told to download a new file, and the emsdk would see that where it would be unpacked had contents, and assumed that even though it wasn't downloaded it must be the same. So we'd silently skip it.
It's useful to always unpack into the same dir since it's easier for people that create their own .emscripten file (the location of emscripten etc. is all fixed under the emsdk), and also it avoids directories accumulating, which each take hundreds of megabytes, so over time it can get burdensome.
An alternative to #247.
cc @floooh

If an archive has not been downloaded, download it and assume its contents are new.

---

emsdk
emsdk_manifest.json

Instead of from mozilla S3.
This should make the core python, java, node downloads work, as we have mirrored them to the new location. I think that should be everything - if we missed something, we will get an error, and so know we need to fix something.
(The non-deps downloads still use a full url to emscripten-releases in the manifest, which is not changed here.)

Change default emsdk download location to emscripten-releases/deps

---

Dockerfile
test.py

Keep the basic workflow test (checking what a user would do to get started) in bash, but otherwise it's more convenient for most tests to be in python.

Refactor test code into python

---

emsdk
emsdk_manifest.json

List the recommended downloads (`latest, latest-upstream`) first, and with version and hash. Then list precompiled things, then list build-from-source things.
Remove old `upstream-clang` build from source, which has been incorrect since llvm switched to a monorepo anyhow. If we want the emsdk to support source builds of llvm, we'll need to fix that - however, as we can use plain upstream llvm anyhow, that shouldn't be hard for developers to build themselves (and normal users will get a precompiled version anyhow).
Remove the option to build fastcomp from source with wasm backend support, as it is horribly old there.
Noticed these issues in https://github.com/emscripten-core/emscripten/issues/8728

emsdk list (list the possible install/activate targets) fixes:

---

emsdk
test.py

(we supported it without -tag-, but that did work before, so fix it for existing users)

Support sdk-tag-X.Y.Z-64bit

---

emsdk

The output now looks like
```
The *recommended* precompiled SDK download is 1.38.34 (048cf9424790cc525a7ea6da340820aae226f3b9).
To install/activate it, use one of:
latest                  [default (fastcomp) backend]
latest-upstream         [upstream LLVM wasm backend]
Those are equivalent to installing/activating the following:
1.38.34
1.38.34-upstream
All recent (non-legacy) installable versions are:
1.38.34
1.38.34-upstream
1.38.33
1.38.33-upstream
```
and after that is the detailed output with the older builds etc.

List emscripten-releases versions in ./emsdk list

---

emsdk
test.py

Also fix the `can_be_installed` which was always broken it seems - it returns True for success or a string for error, but didn't check if the output `is True`.
Includes a test, which hacks up emsdk to make it think it's on 32-bit, and verifies the error and message.

Error on downloading a 64-bit package on a non-64-bit OS

---

emsdk
test.py

The non-git case was not well documented and not tested, and it was broken since we switched the build infrastructure.
In the git case, an update is to do a git pull. In the non-git case, it downloads a zip and unpacks it. The old build infra apparently had builds created for this; instead, I made it download it directly from github. Perhaps we should consider creating builds for this as well eventually?
Also add a test for this, so we never break it again.

Fix ./emsdk update of a *non*-git install

---

emsdk
python_selector

On macOS it's pretty common to hit a problem
```
Error downloading URL 'https://github.com/kripken/emscripten/archive/1.38.25.tar.gz': <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```
When an installation is started. I.e. `./emsdk install sdk-1.38.25-64bit` - this is caused in majority of cases by some problem of openssl and python2 - (some other https downloads work just fine, not sure why GitHub is special)
So this Pull Request will default Python to Python 3, for running `emsdk`

Default Python 3 for running emsdk

---

python_selector

Addresses https://github.com/emscripten-core/emscripten/issues/8792
I've found what's the reason of the strange behaviour of last changes (https://github.com/emscripten-core/emsdk/pull/273). 
In order to reproduce this problem it's needed:
* To don't have python3 installed in system
* To have `pyenv` with installed at least one version from each family, like:
```
pyenv install 3.7.0
pyenv install 2.7.15
```
* To activate a version from python2
```
pyenv local 2.7.15
```
Then we have a strange situation that `python3` is available as a command, but it's just a mock for `pyenv`:
```bash
➜ pyenv versions
system
* 2.7.15 (set by /home/trzeci/Projects/emsdk/.python-version)
3.7.0
➜ which python3
~/.pyenv/shims/python3
➜ python3 --version
pyenv: python3: command not found
The `python3' command …
```

python_selector checks if found python command is valid

---

test.py

The tests for older versions had some copy-paste stuff, that meant we didn't fully test activating them.

Fix old tests

---

emsdk

Fix windows bug with move erroring if the target exists, so installing a second time fails

---

Dockerfile
emsdk
test.py

~~Will only use `ninja` if it is on the path, otherwise uses Makefiles.~~
The user can choose which CMake generator to use by passing the `--generator` option, e.g. `--generator=Ninja` or `--generator="Unix Makefiles"` to `emsdk`.  
Default on *nix systems is `Unix Makefiles`

Support ninja build tool

---

emsdk

Fixes https://github.com/emscripten-core/emsdk/issues/138
As I got from my research and [StackOverflow](https://stackoverflow.com/questions/1951658/sendmessagehwnd-broadcast-hangs), WinAPI `SendMessage` function doesn't return until all receivers have processed the message. So it might hang sometimes, this happens on my machine and some other users report such problem.
We can use `PostMessage` instead of `SendMessage`. Another solution is to use [SendMessageTImout](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessagetimeouta), but I am not sure what constant timeout value we should pass.

Fix 'SendMessage' hanging on Windows

---

emsdk

Windows version of python 3 returns platform.machine() in upper case for AMD64 which wasn't being checked for so added .lower().
Doesn't affect Linux python3 which already worked.

Fix issue with windows install

---

emsdk

Implements what @juj suggested here: https://github.com/emscripten-core/emsdk/pull/274#issuecomment-502447670
After this, the behavior should consistently be: archives are downloaded, unpacked, then deleted immediately. Another install of the same thing will re-download.

List all archive suffixes properly, so we clean up all downloaded archives

---

emsdk
test.py

We got this wrong because we were not using `get_download_target`, so we were trying to delete the wrong file.
Also add a test.
Fixes #320

Properly clean up downloaded zips

---

emsdk

This prevents using archives left behind by mistake in the past.
Fixes #323

Always download archives, since we delete them after use anyhow.

---

emsdk_manifest.json

Apparently this broke on mac: #337

Revert "Update default node version to 10.16.3 (#331)"

---

.flake8
emsdk.py

Now that we have much better testing in CI this kind of change
should be much easier to make with confidence.

Fix a bunch of flake8 warnings

---

emsdk_manifest.json

Turns out 10.16.3 has issues running some emscripten tests due to a
v8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=8347.

Update node version to 12.9.1

---

emsdk.py

Previously we were asserting and generating a stack track if a
download failed.  However the assert is only relevant if the download
succeeds.
Also:
- Remove an unused function
- Remove extra braces from tuple destructuring

Handle missing downloads gracefully

---

emsdk.py

Fix for default NODE_JS in config file

---

emsdk.py

Opening it and saving it in an editor can add a newline, and we have user reports of this happening for users (https://github.com/emscripten-core/emscripten/issues/9651, but I'm not sure why it happens there; this should fix it though).

Strip the tot value from whitespace

---

emsdk_manifest.json

These are part of `releases-fastcomp` but for some reason are not
included in the upstream equivalent.  I imagine they were simply
overlooked.

Add python and java to 'releases-upstream' for windows

---

emsdk.py

Do not attempt to reinstall python if it already exists, since that python may be interpreting the current emsdk.py script that is being executed to do the installation.
At some point in the past the installation model changed to always redownload+unzip over tools that already have installed. That broke emsdk on Windows, as it would attempt to re-unzip python over to the directory where python was actively being executed, resulting in error
```
Downloading: C:/code/emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/WinPython-64bit-2.7.13.1Zero.zip, 41285159 Bytes
Unpacking 'C:/code/emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip' to 'C:/code/emsdk/python/2.7.13.1_64bit'
Unzipping file …
```

Do not attempt to reinstall python if it already exists

---

emsdk.py

With emscripten-releases all the SDKs install the same directory so
this is particularly important for them.

Clobber target directory before extracting SDK tools

---

emsdk_manifest.json
test.py

Rename old fastcomp-based tools to a specific fastcomp- prefixed name to clearly distinguish legacy toolchain

Rename old fastcomp-based tools to a specific fastcomp- prefixed name

---

README.md
emsdk.py
emsdk_manifest.json

It looks like at some point the support for building wasm upstream backend from LLVM source was deleted from emsdk. This PR looks to introduce that support back.
Although when I work on this, I get all sorts of Windows build failures.
First is that Clang-fuzzer does not really build but gets build errors in LLVM trunk. After that it looks like handling of `-DLLVM_ENABLE_PROJECTS="clang"` is broken and one must duplicate it to `-DLLVM_ENABLE_PROJECTS="clang;clang"` for it to work. Trying to build targets libcxx, libcxxabi, libunwind, compiler-rt or polly do not work but they attempt to write to C:\Program Files as an unprivileged user and get access denied. And finally I don't get `wasm-ld.exe` generated, even if I add `lld` target into the build.
This is a bit surprising, I feel like I am …

Build wasm master

---

emsdk_manifest.json

These were missing, original PR only added windows target.

Add upstream-incoming SDK targets for macOS and Linux as well

---

emsdk.py

Remove old workaround that was there to restore %SystemRoot% in PATH on Windows systems that were affected by Emscripten's #4121.
Fixes #414.

Remove old workaround that was there to restore %SystemRoot% in PATH

---

emsdk.py
emsdk_manifest.json

Automatically run `npm install` in Emscripten root directory after installing an Emscripten tool.

Add npm install step as post-build to Emscripten

---

emsdk.py

Fixes: https://github.com/emscripten-core/emscripten/issues/10291
Also fix issue where an old/incorrect version of node could be used
during SDK install since we were preferring activated versions of node.

Use `npm ci` over npm install

---

.flake8
emsdk.py

Fixes: https://github.com/emscripten-core/emscripten/issues/10291
Also fix issue where an old/incorrect version of node could be used during SDK install
since we were preferring activated versions of node.

Hide npm output by default

---

emsdk_manifest.json

This should ensure that BINARYEN_PATH is added to the resulting
~/.emscripten file when building from source:
https://github.com/emscripten-core/emsdk/issues/434
Tested briefly on macOS with `emsdk install sdk-upstream-master-64bit`.

Re-add binaryen dep to upstream-master SDK builds

---

emsdk.py
test.py

- Writes a `.emsdk_version` file to output directories using the name (which contains a version number and/or hash) once all installation steps have completed successfully
- If that file exists, skip downloading/installation hooks.
My primary use case for this is running `emsdk.py install latest` as part of another repository's setup steps - and I want to avoid developers needlessly downloading the same large tarballs every time they run it.

Avoid re-downloading files that are already downloaded

---

docker/Dockerfile
docker/Makefile
docker/README.md

- Dockerfile:
- Use the most recent stable debian (buster) instead of the previous one
- Build version 1.39.11 by default instead of 1.38.43
- Fix small typo in the comments
- Makefile and README.MD: Fix incorrect name of image on dockerhub
(someone probably decided to change this without telling everyone)-

Docker fixes and updates

---

emsdk_manifest.json

Doing this for windows is trickier as we would also need to provide
the python binaries for win32.
Fixes: #470

Re-enable building master from source for linux 32-bit

---

emsdk_manifest.json

I think this should have been part of #395.
Fixes: https://github.com/emscripten-core/emscripten/issues/10904

Remove reference of old clang binary.

---

emsdk.py

Remove VS2015, VS2013, VS2012 and VS2010 remnants, none of these are able to build LLVM anymore. (I think since recent upstream LLVM changes, VS2017 might not be able to either, but not 100% sure about that)
Untested, authored this on a mac host, letting CI see how it works out.

Drop Visual Studio 2015 build support and older

---

scripts/update_node.py
scripts/update_python.py

In both cases updating these is slightly non-trivial so encode
the process in the script.

Add script for updating node and python binaries in google storage

---

emsdk.py
emsdk_env.sh

This allows emsdk_env.sh to work under bash for windows. Without
this emsdk will default to cmd.exe syntax when running on windows
and `source emsdk_env.sh` will not work.

Allow EMCC_BASH to force bash during construct_env

---

.circleci/config.yml
scripts/test.py

It was working previously by accident because the tests were
using the defaults such as $HOME/.emscripten.  However usage of the
emsdk should really only happen in the emsdk environment where
EM_CONFIG dictates the config location (not just using the default).
This change is needed as precursor to making `--embedded` the default
(in this case the config doesn't live in `$HOME/.emscripten`).

test.py should require that the SDK be activated

---

emsdk.py

See https://github.com/emscripten-core/emscripten/pull/11091

Add CACHE setting to config file (for embedded users)

---

emsdk.py

If `is_installed` doesn't return true after install than something
serious went wrong so make this into a warning.
Also, clean up couple of places to make the python code more
readable.

Make installation errors fatal

---

emsdk.py

Ooops, I guess even the most innocent-seeming change can have
unintended consequences. Switching to embedded by default will at
least make this path more tested in the future.
Fixed #497

Fix for parsing existing config in --embedded mode after #495

---

emsdk.py
emsdk_manifest.json

"Legacy" here meaning anything using only < 1.38.0, and anything
using 'nightly' mozilla builds (which have not been done for years).
This also lets us remove node 4.1.1 (but not 8.9.1).

Remove legacy builds

---

emsdk.py
emsdk_manifest.json
scripts/test.py

Now that emscripten uses an in-tree cache directory there is no
need to copy the pre-built libraries around.
See: https://github.com/WebAssembly/waterfall/pull/644
Also for the sake of older versions of emscripten explictly set
EM_CACHE environment variable to point to the in-tree cache
directory.

Update default emscripten cache directory

---

emsdk.py
scripts/test.py

This expands on #460 which added a file in each install dir
with the version, that lets us know not to re-download it. That
didn't integrate with `is_installed`, so it wasn't reported properly,
which this PR fixes.
With this we can remove a hack for python, as we can simply
not install anything if it's already installed (see line 1859).
Also add the "INSTALLED" indicators on the main listings in
"emsdk list". The output can now look like this:
```
To install/activate it, use one of:
latest                  [default (llvm) backend]
latest-fastcomp         [legacy (fastcomp) backend]
Those are equivalent to installing/activating the following:
1.39.16             INSTALLED
1.39.16-fastcomp    
All recent (non-legacy) installable versions are:
1.39.9    
1.39.8    
1.39.7    
1.39.6 …
```

Properly report what is installed in "emsdk list"

---

emsdk.py

I can't see any reason why the embedded mode isn't always preferable.
The emsdk is designed to be used as-is, and per-user customizations
don't make sense.
I'm hoping if this sicks we can just remove this options completely.
This is part of a wider plan to remove the use of the user's HOME
directory completely:
https://github.com/emscripten-core/emscripten/issues/9543

Use embedded configuration by default

---

emsdk.py

This uses LooseVersion from distutils, here is the doc:
> Version numbering for anarchists and software realists. Implements the
> standard interface for version number classes as described above. A
> version number consists of a series of numbers, separated by either
> periods or strings of letters. When comparing version numbers, the
> numeric components will be compared numerically, and the alphabetic
> components lexically.
> ...
> In fact, there is no such thing as an invalid version number under
> this scheme; the rules for comparison are simple and predictable, but
> may not always give the results you want (for some definition of
> "want").
I believe that this should be available in all possible configurations of python, I checked with python2 & 3 on linux. If not, an easy …

Properly sort versions in "emsdk list"

---

docker/Makefile
docker/README.md

Without `--network host` It's impossible to build images (might be some recent addition for docker engine, as I don't recall it was a case before)

Add host network for building image

---

.circleci/config.yml

As per https://github.com/emscripten-core/emscripten/issues/11078 and https://github.com/emscripten-core/emsdk/issues/372.
@trzecieu @sbc100 
Very very rough draft for building the docker image on Circle CI.
**TODO**
- ~~Build various variations of the image? (i.e. I remember emscripten-slim and a ubuntu based version in trzeci's original images.)~~

Build docker image on Circle CI

---

.circleci/config.yml

This change will: 
* Push all future docker images as `emscripten/emsdk:X.YY.ZZ` instead of  `emscripten/emsdk:X.YY.ZZ-upstream`
* Set created tag as `latest`

Updated tagging schema for docker images

---

emsdk.py

This was only ever set to true if the user knew to pass an
undocumented extra argument called "perm".
Split out from #515

Remove unused permanent in construct_env

---

emsdk_manifest.json
scripts/test.py
scripts/update_node.py

It includes an update to v8 7.8

Update nodejs to v12.18.1

---

emsdk.py

docs: change message when running emsdk_env.sh

---

emsdk.py
emsdk_env.bat
emsdk_env.csh
emsdk_env.fish
emsdk_env.ps1
emsdk_env.sh

Remove the optional argument to contruct_env.  It simple if we
always construct the env in the same place.  Avoid using temp files,
and avoid changing directory.

Cleanup emsdk_env scripts

---

emsdk.py

Change EMSDK_SET_ENV to output correct filename for powershell.
Rename write_set_env_bat to write_set_env_script.

Fix set environment script name for powershell

---

emsdk.py

On platforms with no supported binary SDKs to download, find_sdk
can return None which caused a check in the "list" command to fail.
Checking for the return value before making method calls fixes this,
and allows Linux/ARM64 to run "emsdk list" and then build an SDK
from source.
Fixes https://github.com/emscripten-core/emsdk/issues/548

Fix fatal exception in "emsdk list" on unsupported platforms

---

emsdk_env.sh

It is not possible to determine the location of as script that is currently
being sources under a POSIX shell such as dash (the default ubuntu shell).
Only bash has this special BASH_SCRIPT variable.
Needed for #554

Remove bash-ism from emsdk_env.sh

---

docker/Dockerfile

This was an internal script that we used to generate up
until #544.   Now we avoid writing that file at all and
emsdk_env.sh is instead sourced directly.
This should fix the docker CI issues we have been having.

Fix docker build to not depend on emsdk_set_env.sh

---

emsdk.bat

The location of this file is now fixed to living inside the
emsdk directory, not the current working directory.
This was changed back in #540

Update location emsdk_set_env.bat in emsdk.bat

---

emsdk.py

See https://github.com/emscripten-core/emscripten/issues/9543

Remove support for non-embedded mode

---

emsdk.py

The activation message is now IMHO more informative and
actionable:
```
$ emsdk activate latest
Setting the following tools as active:
node-12.18.1-64bit
releases-upstream-e7e39da9c81faecd9ecf44065cee864d76e4e34d-64bit
Next steps:
- To conveniently access emsdk tools from the command line,
consider adding the following directories to your PATH:
$HOME/wasm/emsdk
$HOME/wasm/emsdk/node/12.18.1_64bit/bin
$HOME/wasm/emsdk/upstream/emscripten
- This can be done for the current shell by running:
source "$HOME/wasm/emsdk/emsdk_env.sh"
- Configure emsdk in your bash profile by running:
echo 'source "$HOME/wasm/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
```

Improve activation message

---

emsdk.bat

TIL a couple of things about bat files. God help me.
- Use a single @echo off at the top rather than @ on every line
- Use lowercase names for builtin operation
- Use setlocal/endlocal rather than reseting EM_PYTHON at the end

Cleanup emsdk.bat launcher

---

docker/Dockerfile

Starting from 1.39.20 the `.emscripten_sanity` file has been moved to `upstream/emscripten/cache/sanity.txt`. It also seems that this file is now generated during the `./emsdk activate <VERSION>` command, so it is no longer necessary to call `emcc`.
Resolves #567.

Fix sanity file location within Dockerfile

---

docker/Dockerfile

While I was doing #568, I noticed that the Dockerfile had some inconsistent spaces and indentations. This PR should resolve these inconsistencies, and also slightly improves the Dockerfile by:
- Removing unnecessary dependencies from the build stage;
- Moving the `binutils` installation to the first layer;
- Merging the `ENV` declarations into a single line.
To be merged after: #568.

Cleanup Dockerfile. NFC.

---

docker/Dockerfile
docker/test_dockerimage.sh

Without this emscripten will default to using $HOME for the
emscripten cache rather than the embedded one.

Make emscripten directory world writable

---

emsdk_manifest.json
scripts/update_python.py

The problem is that python can have trouble finding the default
certifcate set on macOS.  The actual bundle is installed by the certifi
package which the requests module uses under the hood.
Fixes #588

Pre-bundle requests module with macOS bundles python

---

emsdk.py
scripts/test.py

I think this is less surprising than continuing to support `latest-fastcomp`
with the last fastcomp release. That's technically correct - the last release
is 1.40.1, and always will be - but when a user asks for "latest" I think they
want something up to date. Instead, give a clear error that indicates how
they can get an actually up to date build, by using upstream.

Error on trying to get latest-fastcomp

---

emsdk.py

related to issue #587
> If nodejs is not installed by `emsdk`, the output ".emscripten" file by `emsdk activate` will look like this.
> 
> ```python
> NODE_JS = ''/usr/bin/nodejs''
> # too many quotes
> ```
> 
> `emcc` fails to execute by this syntax error.
> 
> I think fixing [this line](https://github.com/emscripten-core/emsdk/blob/1.40.1/emsdk.py#L1450) could be a solution.
> 
> ```python
> activated_config['NODE_JS'] = "'%s'" % node_fallback
> # the value will be quoted later again
> ```

Fix `emsdk activate` breaking configuration file

---

emsdk.py

`load_releases_info()` from `emsdk.py` reads `emscripten-releases-tags.txt` into memory and parses it as Json. It is called many times to retrieve info about the sdk. For example `emsdk.py list` will call it 12 times.
Since each call produces the same result I think we could save some reading and parsing by caching the result, thus this pull request :)
Best regards

Parse the releases info only once in emsdk.py.

---

.dockerignore
docker/Dockerfile

We no longer ship the sanify file as part of the SDK but
expect it be generated on first use:
https://github.com/WebAssembly/waterfall/pull/656
Also remove the Dockerfile itself from the docker image if
we include it then whenever you change anything in the
Dockerfile it invalides all the layers and forces a
completely rebuild.  This makes iterating on the image
very slow.

Fix sanity file generation in Dockerfile

---

emsdk.py
emsdk_manifest.json

Newer SDKs don't require this and removing it doesn't break
any older SDKs (it just slows down their first use).

Remove copy_pregenerated_cache

---

emsdk.ps1
emsdk_manifest.json

This adds the missing python locations to emsdk.ps1 so it matches emsdk.bat. 
On Windows, if you add the emsdk dir to the path and use PowerShell as your terminal (which is almost everyone), then any call to "emsdk" will actually use the ps1 files. This means the Python version that is shipped with esmdk is not used!

Add missing python locations to emsdk.ps1

---

emsdk_manifest.json

This is still used for the legacy emscripten tags installation
but the native optimizer no longer exists on master.

Remove native optimizer build from emscripten master install

---

.circleci/config.yml
README.md
emsdk.py
scripts/test_permanent.ps1

Closes https://github.com/emscripten-core/emsdk/pull/468
Fixes #467
This makes ./emsdk activate --global to set user environment variables by default instead of previous system-wide-only activation.
Also removes some magic that implicitly nukes user envvars when system ones are shadowed, as a system admin should understand what's going on when setting envvars. Thus fixes #189 and closes #192.

Set user environment variables permanently by using `--permanent` + deprecate `--global`

---

emsdk.bat

It seems that using ``::`` style comments in bat file function blocks causes weird errors in the command line as it's interpreted as a path.
https://stackoverflow.com/questions/12407800/which-comment-style-should-i-use-in-batch-files/12408045#12408045

Minor fix to emsdk.bat file

---

emsdk.py

When running `source emsdk_env.sh` along with python provided by MSYS2/MinGW the environment gets falsely identified as Linux.
See discussion for details:
https://github.com/emscripten-core/emscripten/issues/12376#issuecomment-702245993

Fix MSYS2/MinGW python mistaking system as Linux

---

emsdk.py

Follow on to https://github.com/emscripten-core/emsdk/pull/625
Fixes https://github.com/emscripten-core/emscripten/issues/12406

Skip installing optional npm deps, but manually install Closure Compiler native package

---

emsdk.py

Reverts emscripten-core/emsdk#630
See https://github.com/emscripten-core/emsdk/issues/632

Revert "Skip installing optional npm deps, but manually install Closure Compiler native package"

---

.circleci/config.yml
emsdk.py
scripts/test_permanent.ps1

Going through the initial setup of emscripten the first time, the first thing I wanted to do was set it up globally to use in visual studio and found that some of the environment variables are not getting applied properly. There are still additional issues with environment variables however since EMSDK_NODE and EMSDK_PYTHON  and PATH will get installed system wide while EM_CACHE and EMSDK will only get installed to user.
FYI: I also ran into some reported issues during my initial setup that didn't block me in the end:
* pywin32 was missing, so I needed to pip install it, maybe add a not in the windows setup documentation.
* ``ERROR: The system was unable to find the specified registry key or value.`` which are not actual issues but should probably be suppressed (trying to delete registry …

Fix Path,EMSDK and EM_CACHE not being set permanently when using --global

---

.circleci/config.yml
emsdk
emsdk_manifest.json

Apparently `Image xcode:9.0 is not supported` these days.

Update mac circleci environment

---

.circleci/config.yml

Apparently we are supposed to do this:
https://discuss.circleci.com/t/old-linux-machine-image-remote-docker-deprecation/37572

circleci: Add explict version to `setup_remote_docker`. NFC.

---

emsdk.py

With 8k the download status is updated way faster than is
necessary.

Increase download chunk size of 256k

---

scripts/test.bat

I have no idea why this argument was included when this
script was first added.  `emsdk_env.bat` does not even pass
its argument into `emsdk.py` so this argument has no effect
here.

Remove used arg in scripts/test.bat

---

docker/Dockerfile

I could imagine that using Git-LFS together with emscripten is not that uncommon, when asset files are pre-loaded.
This PR adds the git-lfs apt package to the docker image. This way, git-lfs doesn't have to be installed during each run in a Github Action build or similar.

Add Git-LFS package to EMSDK Docker image

---

bazel/emscripten_toolchain/emscripten_config
bazel/emscripten_toolchain/wasm_binary.py

fix: bazel/emscripten_toolchain/wasm_binary.py  \`file\` command output without mimetype on MacOS

fix: \`file\` command output without mimetype on MacOS

---

scripts/test.py

We have mac linux and windows bots that run this script
on each of those platforms.  This script already runs
`install latest` so there is no need to re-download these
three different archives on each platform.

Remove redundant testing/downloading

---

bazel/WORKSPACE
bazel/emscripten_toolchain/crosstool.bzl
bazel/emscripten_toolchain/emscripten_config
bazel/emscripten_toolchain/env.sh
emscripten-releases-tags.txt
scripts/test_bazel.sh

This change comes with fairly major change to the bazel toolchain.
- Use pre-built cache that comes with emsdk
- Mark cache as readonly using FROZEN_CACHE
- Pass `--sysroot` to match upstream emscripten change

Release 2.0.13 and update bazel toolchain

---

bazel/emscripten_toolchain/crosstool.bzl
bazel/hello-world/BUILD
bazel/hello-world/hello-world-simd.cc
scripts/test_bazel.sh

I added a small example to reproduce the issue with SIMD header file not found (#699).
```
In file included from hello-world/hello-world-simd.cc:1:
external/emscripten/emscripten/cache/sysroot/include/wasm_simd128.h:10:15: fatal error: 'wasm_simd128.h' file not found
#include_next <wasm_simd128.h>
^~~~~~~~~~~~~~~~
1 error generated.
```
This PR fixes the issue by locating `wasm_simd128.h` in the right directory.

Fix: wrong clang path in Bazel toolchain

---

docker/Dockerfile
emsdk_manifest.json
scripts/test.bat
scripts/test.py
scripts/update_node.py

See https://github.com/WebAssembly/binaryen/issues/3551

Update node version to 14.15.5 (latest TLS release)

---

emsdk_manifest.json
scripts/test_activation.ps1

For Java we use the value in the config file so it doesn't need to be in
the PATH.
For python, all our tools should launch via scripts that check for
EMSDK_PYTHON so having python in the PATH for emsdk users should not be
needed.
The motivation for this is that we don't want to clobber any existing
python or java versions that users might already have in their PATH.
This is the easy part of #705.

Avoid adding our python and java to user's PATH

---

emsdk_manifest.json

To match the branch rename that happened in #693.

Rename llvm-git-master -> llvm-git-main

---

emsdk.py

"emsdk install emscripten-master-64bit" is currently dependent on whether emscripten node is installed or not.
This change allow using system-provided node / npm command to proceed the installation. Also clarify the error message.
Other alternatives:
#640 maybe addresses this for a different reason
I don't think #714 addresses this
Another alternative is to provide node.js in source form (and compile it) if "emsdk install emscripten" must use emscripten node / npm, to which also can address #623

Allow system npm in "emsdk install emscripten"

---

emsdk.py

update-tags is called from two places `update-tags` itself and also
as as part of `update`.   Silently ignoring the absence of git should
only happen in the later case.   If the user explicitly ask for
update-tags we should hard fail as normal.

Move error reporting when git is not found during update-tags

---

emsdk.py

Using the full SDK name was causing a crash here because the
version is not of the form 1.2.3.  e.g:
sdk-releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit

Fix crash attempting to install fastcmp SDK by hash

---

emsdk.py
emsdk_manifest.json

This avoids re-running the post-install scripts when commands such as
`./emsdk install latest` a re-run.  This re-running of npm ci can be
significant slowdown especially during testing and developerment.
Becuase of the refactoring this change change also means we exit ealier
when a given tool fails to install.  In general we want to error out as
early as possible on the first failure so as not to bury it.

Avoid post-install when nothing is installed

---

README.md
docker/Dockerfile
emsdk.py

Its not really very useful to cache the tot release in a local text
file.  Instead just fetch the revsion each time `install tot` is run.
This avoids folks accidentally installing "old" tot releases.
Also, make the output a little less chatty when looking up tot version.

Remove `update-tags` phase

---

emsdk.py

As of #505 all tools write a check a version file so we don't need to
special case vs-tool anymore.

Remove special version check for vs-tool. NFC.

---

emsdk_manifest.json
test/test.py

This matches the branch name that was already updated/renamed.

Rename binaryen-master to binaryen-main

---

emsdk.py
test/test.py

See https://github.com/WebAssembly/waterfall/pull/670

Skip npm step if node_modules already exists

---

docker/Dockerfile

This is principally, for me at least, to be able to include a more up to date version of CMake. Focal has 3.16.3. The Debian Buster based image had CMake 3.13. Installing the most recent CMake from KitWare into that Docker image proved impossible because it had a dependency on a version of libssl not in Buster.
`test_dockerimage.sh` runs successfully using the updated image as does my own project's build.
The size of this image is 1.67GB. The Buster-based image is 1.59GB.
Note that I have left intact all the explicit package installs as I did not want to spend time determining which of them may be installed by default in Focal.
After you merge this PR, how can I determine when the emscripten/emsdk image at docker.com has been updated?

Change base to Ubuntu 20.04.2 LTS (Focal Fossa).

---

README.md
emsdk.py
emsdk_manifest.json

Now that all the components (binaryen, emscripten and llvm) use `main`
as the brnach name is makes sense to give the SDK this name.
Keep backwards compat with the old name but issue a warning when its
used.

Rename sdk-upstream-master SDK to sdk-upstream-main

---

emsdk.py

This is a somewhat cryptic change about VS2017 -> VS2019, I am struggling to find information about this on the web.
It looks like a change in Windows SDK or VS2017 -> VS2019 has shuffled paths around the toolchains, hence what used to be `VCTargetsPath\Common7\IDE\VC\VCTargets` can now be located in `VCTargetsPath\MSBuild\Microsoft\VC\v160\`.
Also not quite sure I understand the role of the `VCTargetsPath` environment variable. The intended role of `VCTargetsPath` is something I don't understand properly, and it is not really well documented.
My impression of this situation is that the `VCTargetsPath` environment variable would have been something that Microsoft Visual Studio has once had as a property that's needed, and CMake was built to rely on it. But as newer Visual Studios came …

Fix search of VCTargetsPath for VS2019 build.

---

.gitignore
emsdk
emsdk_manifest.json
scripts/update_python.py

Fix support for Apple M1. Node.js will still run via Rosetta 2 emulation since they do not yet have M1 support, but Python, LLVM, Emscripten and Binaryen will be native.
In order for Python to actually be native, will need to upload new Python to Google CDN built with update_python.py.

Fix support for Apple M1

---

bazel/emscripten_toolchain/crosstool.bzl
bazel/emscripten_toolchain/link_wrapper.py
bazel/emscripten_toolchain/wasm_binary.py
bazel/emscripten_toolchain/wasm_cc_binary.bzl

This gets us most of the way there for #759.

Bazel add html support

---

emsdk.py

This was set back in commit cea44f475af10c6fde85d4906111a39818e3f134
Fixes #760
A minor change that clears up the confusion when building / packaging emscripten, the default build option does not match up with what was listed in `./emsdk.py`

List "Release" as the default build option

---

emsdk.py
test/test.py

Previously this had to be
```
emsdk install sdk-releases-upstream-HASH
```
The only thing preventing using just the hash was that there was no
default for the backend, so defaulting to upstream fixes this.  And then
we can do
```
emsdk install HASH
```

Simplify the notation for installing by hash to just "emsdk install HASH"

---

docker/README.md

Improve description for the docker image building. 
Closes #748

Correct README.md about building arguments of docker image.

---

emsdk.py

Remove the use of a custom temp directory. That is a bad practice, we should reuse system temp directory instead, that is what it is there for.

Remove the use of a custom temp directory

---

emsdk.py
test/test.py
test/test_activation.ps1
test/test_path_preservation.ps1

This avoid polluting the global environment which makes
side-by-side installational of different emscripten version
harder.
See https://github.com/emscripten-core/emscripten/pull/13954

Avoid setting `EM_CACHE` unless we really need to

---

emsdk.py

Add option --override-repository to allow controlling where git clones happen from.
With this method we can integrate emsdk builds to our CI.

Add option --override-repository

---

emsdk.py
test/test.sh

When we deactivate a tool we also want to remove its environment
variables.   One driver for this is that modern sdks don't set
`EM_CACHE` whereas old ones did and we want to make sure that
`EM_CACHE` gets unset when folks upgrade (and then re-set if
they downgrade).  See #797.

Unset emsdk-related environment variables from inactive tools

---

emsdk.py

This works regardless of the name of the primary branch so that
the code will continue to work if/when we rename `main` to `master`.
See: #805

Switch to `HEAD.zip` when downloading archive from github.

---

emsdk.py

Remove explicit closure install step, the first install command does already seem to install google-closure-compiler-windows at least.
See #802 , #793, #636.
This would help from Linux and macOS testing to see if that works for people. CC also @curiousdannii

Remove explicit closure install step

---

emsdk_manifest.json

This allows emsdk to download the new ARM64 binaries from
the emscripten-releases builders.

Create manifest SDK entries for ARM64 emscripten-releases builds

---

emsdk.py
scripts/update_python.py

This PR resolves four backwards compatibility issues that affects people generating redistributable packages of Emscripten SDK:
1. Set the macOS version to target to macOS 10.11 for LLVM. This enables developers to package up Emscripten SDK on e.g. macOS Big Sur 11.0 machines, but still be able to target older macOS systems. Also fall back the previous Python target from 10.13 to 10.11. macOS 10.11 is chosen because of a) neither Python or LLVM really need any new macOS system SDK functions, but they are pretty self-contained and build fine targeting macOS 10.11, and b) looking at the table https://en.wikipedia.org/wiki/MacBook_Pro#Supported_macOS_releases gives macOS 10.11 the "universal" sweet spot that targets the widest audience.
2. Disable libxml2 from LLVM build with …

macOS and Linux backwards compatibility

---

emsdk.py

Behavior is:
```
$ ./emsdk install 2.0.0
****
Error: You appear to be using the `master` branch of emsdk.
We recently made the switch to using `main`
In order to continue to receive updates you will need to make the switch locally too.
For normal clones without any local branches simply running the following command should be enough:
`git checkout main`
For more information see https://github.com/emscripten-core/emsdk/issues/805
****
$ echo $?
1
```
See #805

Error on the master branch. See #805

---

emscripten-releases-tags.txt
emsdk.py
test/test.py

Also, improve reporting of version resolution. e.g.:
```
$ ./emsdk  install sdk-latest
Resolving SDK alias 'latest' to '2.0.23'
Resolving SDK version '2.0.23' to 'sdk-releases-upstream-77b065ace39e6ab21446e13f92897f956c80476a-64bit'
Installing SDK 'sdk-releases-upstream-77b065ace39e6ab21446e13f92897f956c80476a-64bit'..
...
```
Should help with #836.

Improve emscripten-releases-tags.txt to support mutliple aliases

---

emsdk.py
test/test.py

an alternative approach to #833.
> this fixes the wrong behavior of emsdk:
> The command `emsdk install releases-upstream-<commit>-64bit` should install emscripten only, but `expand_sdk_name()` rewrite the args so it behaves same as `emsdk install sdk-releases-upstream-<commit>-64bit`.
as #833 broke extra_release_tag, this change uses a more straightforward way: if name starts with "releases-", we treat this as a tool instead of sdk.
The current code is bug prone (for example, if a tool's name is exactly length of 40, it will be treated as a "version" of SDK), but I don't think there is a easy fix as several places depends on global variable extra_release_tag. the ideal fix is to have a strict definition of whether a name is a tool or sdk, and perform a check based on that. considering …

bugfix: allow to install SDK binaries alone

---

emsdk.py
test/test.py

Previously if a tool (any part of an SDK) was not installed
we would issue a warning and continue to active without returning
non-zero.
This meant doing `emsdk install 2.0.0 && emsdk activate latest`
would appear to be work aside from the warning messages about
latest not being installed.
This is especially annoying since we dropped support for side
by side SDK installations.  The following sequence is no longer
valid and we want to make that clear by erroring out:
```
$ emsdk install 2.0.1
$ emsdk install 2.0.2
$ emsdk activate 2.0.1
```
Since 2.0.2 replaces 2.0.1 on the filesystem the active here
could fail hard rather than just warning.

Error out on attempt to activate a missing tools

---

bazel/emscripten_toolchain/link_wrapper.py

This should help debug cases when the link_wrapper is not invoked correctly.

Print sys.argv when link_wrapper.py is invoked incorrectly

---

bazel/emscripten_toolchain/link_wrapper.py

When linking with `-o filename` (such as in various CMake build checks), the parameter passed to the linker is a temporary file, and it is passed as a bare filename (i.e. relative path without a `'/'`). In such cases, `outdir` would have been the empty string, and the final `tar` command would fail (actually the call to `subprocess.check_call(…)` is what fails).

Support linking with `-o filename`

---

bazel/emscripten_toolchain/link_wrapper.py

Closes https://github.com/emscripten-core/emsdk/issues/887
The path to `llvm-objcopy` is incorrect from what I can tell. I've tested this change using `local_repository` and I am now able to successfully build with `-s SINGLE_FILE=0` with separate .js, .wasm and .debug.wasm files.

[Bazel] Fix llvm bin path

---

emsdk_manifest.json

This was missing from emsdk_manifest.json and should alow older fastcomp
SDKs to be install on M1 apple hardware (in emulation mode).
Fixes: #889

Add arm64 fastcomp releases to emsdk_manifest.json

---

emsdk.py

Fix passing -DLLVM_ENABLE_PROJECTS directive to CMake - it does not want to see double quotes in the field passed to it.
That was the source of the peculiar Windows vs Linux build issue: on Windows `-DLLVM_ENABLE_PROJECTS="clang;lld"` would pass `"clang` and `lld"` targets to the build, and LLVM would ignore it altogether. That is why `-DLLVM_ENABLE_PROJECTS="clang;clang;lld;lld"` "fixed" it, as it would pass `"clang`, `clang`, `lld` and `lld"` to the build, and LLVM would ignore the nonmatching strings altogether.
It looks like upstream LLVM CMakeLists.txt has added validation to no longer ignore nonmatching project target strings, so it has started to complain about the above directive.

Fix passing -DLLVM_ENABLE_PROJECTS directive to CMake

---

emsdk.py
scripts/update_python.py

Apparently 10.11 is no longer good enough to run the latest version of
binaryen.  Specifically since binaryen switched to using std::variant it
now fails to build with this set to 10.11.
This is also the version used on the emscripten-releases CI which builds
the emsdk binaries:
https://chromium.googlesource.com/emscripten-releases/+/refs/heads/main/src/build.py#673

Update CMAKE_OSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

emsdk.py

Untested, but the original code looked wrong.

Remove all vs-tool references

---

.dockerignore
docker/README.md

This PR simplifies and improves the `.dockerignore` file by excluding everything and using a allow list to include the things that are really needed.
The reason for this is that the `*/*` syntax in `.dockerignore` still causes empty directories.
```bash
$ docker run -it emscripten/emsdk:2.0.34 ls -l /emsdk
total 224
-rw-r--r-- 1 root root   1326 Nov  4 21:53 LICENSE
drwxr-xr-x 2 root root   4096 Nov  4 21:53 bazel
drwxr-xr-x 2 root root   4096 Nov  4 21:54 docker
-rw-r--r-- 1 root root   5147 Nov  4 21:53 emscripten-releases-tags.json
-rwxr-xr-x 1 root root   1630 Nov  4 21:53 emsdk
-rw-r--r-- 1 root root 124970 Nov  4 21:53 emsdk.py
-rw-r--r-- 1 root root   1975 Nov  4 21:53 emsdk_env.sh
-rw-r--r-- 1 root root  30131 Nov  4 21:53 emsdk_manifest.json
-rw-r--r-- 1 root root     25 Nov  4 …
```

Simplify and improve .dockerignore. NFC.

---

.circleci/config.yml

See https://github.com/emscripten-core/emsdk/pull/936
See https://github.com/WebAssembly/binaryen/issues/4353

Pass `-Wno-unused-variable` when building binaryen during CI

---

bazel/emscripten_toolchain/link_wrapper.py
bazel/emscripten_toolchain/wasm_binary.py

This will change the result of --config=wasm builds that were previously outputting a single file.
Helps prepare for windows support (#814) and removes the need for #929 to add an external python dep.

Always output a tarball from cc_binary to simplify logic.

---

bazel/emscripten_toolchain/crosstool.bzl

Bazel has three compilation modes, fastbuild, dbg and opt. Docs [here](https://docs.bazel.build/versions/main/user-manual.html#flag--compilation_mode).
Copying the definitions here for reference:
```
- fastbuild means build as fast as possible: generate minimal debugging information (-gmlt -Wl,-S), and don't optimize. This is the default. Note: -DNDEBUG will not be set.
- dbg means build with debugging enabled (-g), so that you can use gdb (or another debugger).
- opt means build with optimization enabled and with assert() calls disabled (-O2 -DNDEBUG). Debugging information will not be generated in opt mode unless you also pass --copt -g.
```
Currently in the emscripten bazel toolchain, dbg seems to be doing the right thing (`-O0 -g`). But fastbuild is optimizing at -O2 when it is …

Canonical optimization levels in bazel toolchain

---

emsdk.py

I have been switching Emscripten versions quite a few times, and emsdk always downloads the binaries. So this adds the environment setting EMSDK_KEEP_DOWNLOADS, which keeps the downloaded archives around.
This also includes a documentation commit for some other EMSDK_* env-vars and one minor typo fix, which I didn't test, but seemed obviously broken.

Optionally keep the downloaded archives

---

bazel/revisions.bzl

I'm not sure how that wrong was added by the create_release script.

Fix for windows checksum in bazel/revisions.bzl. NFC

---

emsdk.py

When invoking "emsdk help", there is a typo/grammatical error in the second to last paragraph.
See also:
https://github.com/emscripten-core/emsdk/issues/957

Correct typo in "emsdk help" message.

---

docker/Dockerfile
emsdk_manifest.json
scripts/update_node.py
test/test.py

The newer versions of eslint require 14.17.0 or above.  This
updates our node version to the latest in the 14.XX series.
I don't expect any user-visible changes.

Minor node version update v14.15.5 -> v14.18.2

---

emsdk.py

These days this argument really means `install_even_if_directory_exists`
(at least since #9300).
However, by the time we call `download_and_unzip` we have already checked
that `is_installed()` is false so we know we want to install for sure.
If the installation directory already existed and contained the correct
contents we would never get as far as `download_and_unzip`.

Remove `download_even_if_exists` argument to download_and_unzip

---

bazel/emscripten_toolchain/crosstool.bzl

It breaks @emsdk in workspaces that have this feature enabled.
The following error appears when using the latest commit:
cc_toolchain '@emsdk//emscripten_toolchain:everything' with
identifier 'emscripten-wasm' doesn't define a tool path for 'dwp'
The following error appears after adding `emdwp` tool and scripts:
output '*.dwo' was not created
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

Don't advertise "per_object_debug_info" feature in Bazel.

---

emsdk.py

This is required to build binaryen since
https://github.com/WebAssembly/binaryen/pull/4466

Add `git submodule update` when doing a git checkout

---

bazel/BUILD
bazel/WORKSPACE
bazel/emscripten_deps.bzl
bazel/emscripten_toolchain/emscripten_config
bazel/revisions.bzl
scripts/update_bazel_workspace.sh

Add `macos_arm64` as a supported platform.

Support Bazel builds on Apple silicon

---

emsdk.py

We don't have any tools or SDK with this attribute.  The last ones were removed in #395

Remove unsed 'windows_install_path'

---

emsdk.py

Is slightly less typing than os.environ.get().
Followup to #1004.

Consistent use of os.getenv. NFC

---

emsdk_manifest.json
scripts/update_python.py

Previously we were using the "embedded" version python which has caused
us a few problems over time.  Currently the issue is that it does not include
pip.  This is a more normal distribution of python that does include pip.
Fixes https://github.com/emscripten-core/emscripten/issues/16466

Switch to nuget python package for windows

---

emsdk.py
emsdk_manifest.json

Thanks for @otterley for doing that hard work of actually building these binaries.
I basically uploaded them and then did and confirmed they are installable have have the right architecture:
```
$ EMSDK_ARCH=aarch64 ./emsdk install 3.1.7
$ file upstream/bin/clang-15 
upstream/bin/clang-15: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[xxHash]=15798223cc2ffa5f, not stripped
```

Add prebuilt binaries of 3.1.7 for linux/arm64

---

emsdk.py

Regarding the change to `content_exists`, we only support tools that
are directories full of files, there is no such thing as a tool that
is just a single file and not a directory.

Minor python code cleanup

---

emsdk.py

Emsdk is unable to build Binaryen from source on macOS since Binaryen adopted new libstdc++ that required a newer macOS, issue https://github.com/WebAssembly/binaryen/issues/4299
Bump the minimum build requirement up to that version.

Fix macOS build

---

emsdk.py

This was introduced by mistake in #996 and cause `Emsdk.test_no_32bit` to fail.

Remove non-ascii char from emsdk.py. NFC

---

emsdk.py

We don't have any tools that are just one file, and indeed we
assume these days that tools install to their own directory.

Remove unused codepath for single-file tools. NFC

---

emsdk.py

Running ` . ./emsdk_env.ps1` on Linux PowerShell (`pwsh`) only output `Setting environment variables`, but **none
of these variables are set actually**.
```pwsh
PS /home/kyaru/projects/emsdk> . ./emsdk_env.ps1
Adding directories to PATH: ...
Setting environment variables: ...
PS /home/kyaru/projects/emsdk> emsdk
emsdk: The term 'emsdk' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
Decide whether to call `write_set_env_script` or not by checking current shell, not platform.
The script works on all platforms.
```pwsh
PS /home/kyaru/projects/emsdk> . ./emsdk_env.ps1
Adding directories to PATH: ...
Setting environment variables: ...
PS …
```

Set environment for powershell on all platforms

---

emsdk.ps1

Fixes: https://github.com/emscripten-core/emsdk/issues/1023 
The downloaded location for python on windows does not match the manifest and hence will not be found.  The system will attempt to default to python found in the path.  (although I think the Powershell for that fallback mechanism does not work in strict mode - fails with `The variable '$EMSDK_PY' cannot be retrieved because it has not been set.` - another story)  .  
This PR adds the location I have observed on my machine for the download and install location of Python to emsdk's search list

Add windows download location to python search path - to match manifest

---

emsdk.py

Cache git executable search into a variable. This helps reduce noise in the verbose debug logging output messages when EMSDK_VERBOSE=1 is enabled.

Cache git executable search into a variable.

---

emsdk.py

Fix native Closure Compiler to work.
Reverts my earlier PR #803 which was a great mistake, as it caused Emscripten to silently fall back to Java version of the Closure Compiler.
After this PR, Closure Compiler will work on user platforms that do not have Java installed.
Also forcibly remove Java version of Closure Compiler on systems where installing the native version succeeds, in order to save on disk size.

Fix native Closure Compiler to work.

---

emsdk.py

Enable building LLVM with about-to-be deprecated toolchains for best chance of succeeding with the build.

Enable building LLVM with about-to-be deprecated toolchains

---

emsdk.py

We are experiencing an issue at our Unity CI with building Binaryen: https://github.com/WebAssembly/binaryen/issues/4588
It seems that for end users, disabling -Werror is a good general measure to enable wider chance of success to build. Emsdk installations are unlikely to be used by Binaryen developers to iterate on Binaryen development, so it is not necessary there?

Pass -DENABLE_WERROR=0 when building Binaryen

---

bazel/emscripten_toolchain/BUILD.bazel

Which of these exists depends on the version of rules_nodejs being used.
Fixes https://github.com/emscripten-core/emsdk/issues/1020.

Conditionally use `@nodejs_host` or `@nodejs`

---

.circleci/config.yml

Using `bazelisk` instead of an outdated version of bazel on macOS should unblock CI failures for #1036 and #1047

Using bazelisk on macOS CI

---

bazel/emscripten_deps.bzl

With emsdk 3.1.13, I was unable to use Bazel compile [CanvasKit](https://github.com/google/skia/blob/main/modules/canvaskit/BUILD.bazel) locally in release mode or remotely in either debug or release mode.
Some files were missing from the specification, as [mentioned here](https://github.com/emscripten-core/emsdk/pull/1045#issuecomment-1121444545).
By specifying a few more files, it now works locally and remotely, while still being significantly faster than 3.1.0 (before #1045 landed).

Add additional files necessary for building with closure and on RBE

---

emsdk.py

The `//?/` prefix does not work in the MSYS environment.
Excluding MSYS from the windows fix worked for me to install emscripten.

Exclude msys from path fix function.

---

bazel/revisions.bzl
emscripten-releases-tags.json

3.1.18 had a bad release binary on ARM64 Mac so push an updated version of the release.

Version 3.1.18 update

---

emsdk.py

Without this the recommended way to silence emsdk_env was to pipe its
stderr to /dev/null.. but then you also loose potentially useful error
message.
Fixes: #946

Add EMSDK_QUIET to make emsdk_env less chatty

---

docker/Dockerfile
emsdk.py
test/test.py
test/test_activation.ps1
test/test_path_preservation.ps1

Newer versions of emscipten, starting all the way back in 1.39.13, can automatically locate the `.emscripten` config file that emsdk creates so there is no need for the explicit EM_CONFIG environment variable.  Its redundant and adds unnessary noisce/complexity.
Really, adding emcc to the PATH is all the is needed these days.
One nice thing about this change is that it allows folks to run whichever emcc they want to and have it just work, even if they have
configured emsdk.   Without this change, if I activate emsdk and I run
`some/other/emcc` then emsdk's `EM_CONFIG` will still be present and
override the configuration embedded in `some/other/emcc`.
e.g. in the same shell, with emsdk activated, I can run both these commands and have them both just work as expected.
```
$ emcc --version
$ …
```

Avoid exporting EM_CONFIG for modern SDK versions

---

emsdk.py

At Linaro, [Windows on Arm](https://www.linaro.org/windows-on-arm/) team is helping open source projects to enable this platform. We spent some time to work on dart-sdk.
A few days ago, a regression was found. [Dart](https://github.com/dart-lang/sdk) started to use emscripten for their dart2wasm module.
This fail to build under Windows on Arm, because emsdk can't find a toolchain to download (when having an arm64 python on the PATH). This PR adds a fallback to download an x64 version instead (supported via emulation from windows 11).

Use x64 version for Windows on Arm

---

bazel/.bazelrc
bazel/BUILD
bazel/README.md
bazel/WORKSPACE
bazel/bazelrc
bazel/emscripten_toolchain/BUILD.bazel
bazel/emscripten_toolchain/toolchain.bzl
bazel/emscripten_toolchain/wasm_cc_binary.bzl
bazel/test_external/.bazelrc
bazel/test_external/WORKSPACE
bazel/toolchains.bzl

Fixes #984. However, the way I have done it requires `--incompatible_enable_cc_toolchain_resolution` and no longer supports `--crosstool_top=...`. I'm not sure how to support both at the same time. If that's necessary, can someone give me pointers on how to do it?

[bazel] Switch to platforms-based toolchain resolution

---

bazel/emscripten_toolchain/wasm_cc_binary.bzl

The `name` attribute for [rule](https://bazel.build/extending/rules#dependency_attributes) will be deprecated in future bazel releases.
See:  [incompatible_remove_rule_name_parameter](https://github.com/bazelbuild/bazel/issues/16301)
To prepare for bazel 6, let's remove the attribute.

remove "name" attribute from bazel rules

---

docker/Dockerfile

Done to upgrade CMake from [3.16.3](https://packages.ubuntu.com/focal/cmake) to [3.22.1](https://packages.ubuntu.com/jammy/cmake).
Motiation: [CMake 3.21 or newer](https://doc.qt.io/qt-6/cmake-get-started.html) is needed to build the Qt 6 sources with emscripten.
CI is failing with a code signing error. I suspect that this is due to https://github.com/docker/docker-install/issues/244, which is fixed by updating the  Docker version on the CI node.

Change base to Ubuntu 22.04 LTS (jammy)

---

bazel/emscripten_toolchain/toolchain.bzl
bazel/emscripten_toolchain/wasm_cc_binary.bzl

This allows building with `--features=standalone_wasm` into a WASI binary.

Add standalone_wasm feature to bazel emscripten_toolchain

---

.circleci/config.yml

Workaround for https://github.com/emscripten-core/emsdk/issues/1153.

Pin Windows CI to Bazel 5.4.0

---

emsdk.py
emsdk_manifest.json
test/test.py
test/test.sh

Folks that want to work with fastcomp will now need to use an older checkout of emsdk.

Remove fastcomp SDK and fastcomp build rules

---

emsdk.py
emsdk_manifest.json
test/test.py

This name existed to distinguish the SDK from fastcomp, but as of #1165, we no longer support fastcomp.

Remove `-upstream` component of SDK names

---

emsdk.py

This PR does the following:
1. Add support for building Emscripten with Visual Studio 2022
2. Remove some code duplication in different places around VS version selection
3. Migrate to using `cmake --build` also when building on Windows. Historically we didn't use `cmake --build` because it was unable to find where MSBuild.exe resided, but it looks like those problems are long gone.
4. To enable `cmake --build` on Windows, leverage the MSBuild 'Multi-ToolTask' feature CL_MPCount to saturate project builds properly to 100% CPU usage so building LLVM builds different cpp files in parallel.

Add support for Visual Studio 2022

---

emsdk.py

Looks like the CI did not fail on an error from the previous PR, but just left the tasks hung. I misinterpreted the two copies of each task (one green, another yellow hung) as a CI fluke, but it might be caused by this typo in refactor.

Fix args ordering in LLVM build from previous commit

---

emsdk.py

Remove support for building with Visual Studio 2017. Since Jan 29, 2022, upstream LLVM has required VS2019 or VS2022 to build. So it has not been possible to build emsdk from source with VS2017 for a year. https://github.com/llvm/llvm-project/commit/058c5dfc78cd1a1a6075bba9799e63f3ec871c0d
I'll rebase this to main once #1177 lands, but want to get the the test suite going already now.

Remove Visual Studio 2017 support

---

emsdk.py

We have an existing `version_key` helper function for sorting versions.
It also does a better job, producing output like:
```
All recent (non-legacy) installable versions are:
3.1.31
3.1.31-asserts
3.1.30
3.1.30-asserts
3.1.29
3.1.29-asserts
```
Rather than:
```
All recent (non-legacy) installable versions are:
3.1.31
3.1.30
3.1.29
3.1.28
3.1.27
```
(with -assert versions listed after 3.1.0)

Improve ordering in `emsdk list`

---

emsdk.py

This PR add support for Visual Studio Build Tools 2022 (Preview) compilation of packages using emsdk.py on and for Windows Arm64.

Windows Arm64 support for emsdk.py only

---

emsdk.py

This PR just removes the unused `build_target_platform` parameter from `make_build()` function in `emsdk.py` as a follow up of https://github.com/emscripten-core/emsdk/pull/1186 PR.

Remove unused build_target_platform parameter from make_build

---

README.md

- Remove reference to `~/.emscripten`.  We no longer use the home directory to store config information by default, either in emscripten or in emsdk.
- Remove some references to `The Emscripten Command Prompt`.  While I suppose this is referring to the windows-only `emcmdprompt.bat`, and I suppose it means "any shell where `activate` has been run", I think its more clear to simply avoid using the term.

Update some stale information in README.md

---

bazel/emscripten_deps.bzl

Added some files to linker filegroup so that Bazel can build successfully in certain scenarios.
- llvm-dwarfdump (needed for `-gsource-map`)
- llvm-mc (`--embed-file`)
- wasm-ctor-eval (`-sEVAL_CTORS=1`)
- wasm-split (`-sSPLIT_MODULE=1`)
- wasm2js (`-sWASM=0`)

Add missing binaries for bazel

---

emsdk.py
emsdk_manifest.json

If the user already has a version of node in their PATH don't clobber it.  This doesn't effect emscripten since the version of node we use there is controlled via the config file, not via PATH.
This change was originally proposed in #714 and we decided against it because there was some danger that it might confuse some users.  However since we closes #714 more and more users have been frustrated buy the status quo.  I also looked into several options for allowing users to opt out explicitly, but they all seems to have the same problem which is that the users don't want their version of node shadowed in the default case.
Part of fix for #705.

Only add node/bin to user's PATH if one is not already found

---

bazel/BUILD
bazel/emscripten_deps.bzl
bazel/emscripten_toolchain/emscripten_config
bazel/revisions.bzl

I could find that there are some prebuilt Linux/arm64 binaries out there, but that their version trails a bit behind and not supported in the bazel rules. This pr aims to change the latter bit.
My usecase is a bazel+emsdk build in a Docker build (unfortunatly can't just build the container directly from bazel). While this works fine in our CI system, locally I'd have to build with docker's `--platform=linux/amd64` which is unbearably slow with bazel in it. Since there are arm64 binaries for linux, I'd like to be able to use those!

Add linux/arm64 support to bazel rules

---

docker/Dockerfile
emsdk_manifest.json
scripts/update_node.py
test/test.py

This is the current v15 release and updating to v15 or above will allow
is to disable and possibly completely remove the
`NODEJS_CATCH_REJECTION` setting in emscripten.  This setting is a
workaround for the fact the older node versions will return exit with 0
on unhandled promise rejection.
The downside to updating the version used by emsdk and therefore the
version against which we do all our emscripten testing is that we
potentially loose some coverage of compatability with older versions.
In practice I don't think we have seen a node compat issue in many
years.  The limits on the JS output produced by emscripten are all
related to targeting older browsers which tend to be a lot older than
any of the node versions we want to target.

Update node version 14.15.5 -> 15.14.0

---

.circleci/config.yml

This runner is faster and more efficient.
Also factor the mac configuration into an executor.

Update mac builders to use Circle's gen2 mac runner

---

docker/Dockerfile

The fastcomp backend was removed in Emscripten v2.0.0.
Split out from PR #1220.

Docker: remove remnant of fastcomp

---

docker/Dockerfile

Docker: remove redundant `EMSDK_NODE` env

---

emsdk.py
emsdk_manifest.json

This seems like more commonly known/used name for the architecture these days.

Prefer `arm64` over `aarch64` internally. NFC

---

emsdk.py

Add a warning when trying to install linux-arm64 binaries

---

.circleci/config.yml
emsdk.py
test/test_node_path.sh

The first time around `node` was being correctly added to the PATH, but the second time around this code was observing the emsdk copy of node in the PATH and assuming it could be skipped.
Fixes: #1240

Fix `activated_path_skip` on repeated running of `emsdk_env.sh`

---

.dockerignore
docker/Dockerfile
docker/Makefile
docker/entrypoint.sh
docker/test_dockerimage.sh

In favor of `/etc/bash.bashrc`, which is only read for interactive shells.

Docker: use a entrypoint script

---

scripts/create_release.py

Having used this script for a while now I'm not sure there is any point if leaving this last step as a manual push.

Have create_release.py push the new branch automatically

---

bazel/BUILD
bazel/emscripten_toolchain/wasm_cc_binary.bzl

Problem: https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/157#discussion_r1277763118
After discussion, we decided to target `@platforms//os:wasi` based on attr.standalone.

wasm_cc_binary: Specify a default OS. Allow users to override platform.

---

bazel/README.md

Mark the build files as using the starlark language so they have the correct syntax highlighting.

Add starlark highlighting to Bazel readme

---

.circleci/config.yml
.flake8
scripts/create_release.py

Flake8's INI config file format requires commas after each line. Because our file didn't have them, the exclude list
wasn't set up correctly, and the `--extend-exclude` flag wasn't working. This PR fixes the .flake8 file.
Also, update flake8 to the latest version available (because version 3.8 is required to get the --extend-exclude flag)
and use the flag to exclude the files in the scripts/ directory from the python2 linter (since the scripts are python3).

Fix the format of the .flake8 file, and exclude the script directory from the py2 linter

---

bazel/emscripten_toolchain/BUILD.bazel

Fixes #1273. This was broken by #1045 with the comment "* all_files not needed?" They were needed.

[bazel] populate all_files

---

emsdk.py
scripts/update_bazel_workspace.py

This should have been part of #1235

Update file extension used by create_release script

---

bazel/emscripten_deps.bzl

This is the simplest solution to my problem described in #1294.
I'm happy to change this to something more specific, e.g. by exporting only the files I currently need, but it seems like having an :all target is the most future-proof way here.
Closes #1294.

[bazel] Add an :all target to binary repos

---

emsdk.py

Add suggestion to install using `--permanent` or `--system` on windows.  NFC

---

emsdk.py
emsdk_manifest.json

We no longer support building fastcomp-based SDKs

Remove logic build building native asm.js optimizer. NFC

---

bazel/emscripten_toolchain/link_wrapper.py

Fixes #1181. `os.rename()` has different behaviors on Windows vs Linux, using `os.replace()` instead fixes the
issue when a new build is created when previous files exist from an older build.
I'm not sure if this is the best way to do this though since there's the method `move_with_overwrite()` in emsdk.py which does what `os.replace()` is supposed to do. Regarding atomicity, according to [python documentation](https://docs.python.org/3/library/os.html#os.replace), `os.replace()`'s renaming is atomic as a POSIX requirement, but Windows isn't fully POSIX compliant.
https://github.com/emscripten-core/emsdk/blob/8822664a145391eee7cb57f9db7ba3705e19f2fe/emsdk.py#L547-L553

Fix FileExistsError on subsequent bazel builds on Windows

---

emsdk.py

`COMPILER_ENGINE` was completely removed from emscripten in https://github.com/emscripten-core/emscripten/pull/9469.
`JS_ENGINES` is only used/needed for testing and is no longer needed as of https://github.com/emscripten-core/emscripten/pull/9542.

Remove JS_ENGINES and COMPILER_ENGINE from config file

---

.circleci/config.yml
docker/Makefile

This means that CI run that update `latest` actually test the thing we are about to ship.
We recently had a case where `latest` was broken but `tot` was fixes and we accidentally shipped a broken SDK version (#1353).

CI: Build `latest` docker image rather than `tot`

---

emsdk.py
test/test.py

This is especially important on macOS where `urllib` can fail to verify certificates.
See https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore
Fixes: #1207, #85, #1356, #1357, #1358

Prefer `curl` for downloading files over `urllib`

---

bazel/BUILD
bazel/MODULE.bazel
bazel/README.md
bazel/deps.bzl
bazel/test_external/MODULE.bazel

I noticed that @googlewalt added `@platforms//os:emscripten` [LINK](https://github.com/bazelbuild/platforms/commit/6b04b816a0edc09e1a3ad4a094177e181a2a1803), now we can update the `platform_wasm`.

(bazel) Set @platforms//os:emscripten for platform_wasm

---

bazel/emscripten_toolchain/wasm_cc_binary.bzl

Usage would be something like:
```
filegroup(
name = "hello-world-tarball",
srcs = [":hello-world-wasm"],
output_group = "_wasm_tar",
)
```
Fixes #1382

[bazel] add tarball as an optional output

---

docker/Dockerfile
emsdk_manifest.json
scripts/update_node.py

Node v18 is that current LTS release of node and v18.20.3 is the latest release of v18.
This change means that emsdk is no longer installable on Ubuntu/Bionic 18.04, and we now require Ubuntu/Focal 20.04.
See: #1183
Fixes: #1173

Upgrade node from v16.20.0 to v18.20.3

---

emsdk

Since we use curl now (#1355) this should no longer be needed.

Remove setting of SSL_CERT_FILE from emsdk launcher script

---

bazel/emscripten_toolchain/toolchain.bzl

[WASM Relaxed SIMD](https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md) has been supported by LLVM and used in the XNNPACK acceleration library in bazel build, see [reference](https://github.com/google/XNNPACK/blob/master/build_config/BUILD.bazel#L169).
Add this feature in bazel toolchain so that it can be recoginized in config similarly to the WASM SIMD feature.

[Bazel] Add feature to support WASM Relaxed SIMD

---

bazel/emscripten_toolchain/link_wrapper.py
bazel/emscripten_toolchain/wasm_cc_binary.bzl

The allowed extension list in `link_wrapper.py` and in `wasm_cc_library.bzl` have been updated in order to support files with the `.aw.js` extensions that are generated when users set `-sAUDIO_WORKLET` compiler/linker flag.
Related issues:
- #1399

[Bazel] Let audio workout bootstrap js file be generated.

---

bazel/emscripten_toolchain/toolchain.bzl

This removes `-Werror` set by default, thus conforming with default bazel cc toolchain.
Part of:
- #1400

Sets wasm_warning_as_error disabled by default.

---

.circleci/config.yml
scripts/get_release_info.py
test/test_bazel.sh
test/test_bazel_mac.sh

Also switch bazel-mac to the arm64 config.
The CircleCI Intel mac config will be turned down soon.

Remove Intel mac CircleCI configuration

---

emsdk.py

Also move some code outside of the `using` block.

Add some logging after download is finished. NFC

---

bazel/emscripten_toolchain/link_wrapper.py

Ensure temporary files have proper unique names for bazel builds.

---

emsdk.py
emsdk_env.fish

I faced the same issue mentioned in #1299, this PR fixes the issue by taking in account specific `set` and `unset` syntax for Fish shell.
The post install instruction (i.e : `./emsdk activate latest`) provides wrong instructions in Fish shell and Cshell cases. 
This should be fixed by this PR too, although the code is a bit redundant and it could be more cleaner. 
The [website instruction](https://emscripten.org/docs/getting_started/downloads.html#installation-instructions-using-the-emsdk-recommended)  have the same issue, but I guess user with specific shell will be able to manage.

fix: improve Fish shell support (and Cshell)

---

emsdk.py

Turns out this is what was causing the OOM when building binaryen since we were clobbering the EMSDK_NUM_CORES environment variable by mistake.
See #1429

Add missing comma from #1429

---

.github/workflows/create-release.yml
scripts/create_release.py

The action runs the existing create_release.py script in a new mode created for github actions. Rather than using local git commands, it uses a public action for creating a PR in the repository. The action can be triggered from the website or via the CLI tool, for example
gh workflow run create-release.yml -R emscripten-core/emsdk -F lto-sha=abc123 -F nonlto-sha=234567

Add a github actions workflow to create a release PR

---

.github/workflows/tag-release.yml

For commits created by the new create-release.yml workflow, we can add the corresponding release tag. This only runs for changes to the tag JSON file (and the workflow itself) and only acts on changes created by the automation (so that it won't interfere if we want to do things manually).

Add Actions workflow to automatically create release tags

---

.github/workflows/create-release.yml
.github/workflows/tag-release.yml
scripts/get_emscripten_revision_info.py

This PR add several features to release automation:
1. The existing tag-release job has an output that indicates whether the triggering commit 
is a release (i.e. whether it matches the regex)
2. The new followup job runs a new script which fetches the recent emscripten-releases
revisions, reads the DEPS file from the 'latest' release in emscripten-releases-tags.json
to find the corresponding emscripten revision and writes it into the environment
2. The final step reads the emscripten revision from the environment and creates a
workflow_dispatch event to run the tag-release.yml job on the emscripten repo

Automatically dispatch emscripten release tag action

---

emsdk.py
scripts/update_python.py

Remove temp zip after uncompressing in update_python.py to avoid confusing it with the output artifact zip. Adjust comments.

Remove temp zip after uncompressing in update_python.py

---

scripts/update_node.py

This allows running the script locally.
Is there some kind of automated script that needs a matching update, or was this always run manually?

Only upload node with gsutil in update_node.py if --upload is passed.

---

docker/Dockerfile
emsdk_manifest.json
test/test.py

Update Node from 18.20.3 LTS to 20.18.0 in precompiled releases. This does have an effect of retroactively updating Node version also to old releases, but this is expected to be fine.

Update Node from 18.20.3 LTS to 20.18.0 in precompiled releases.

---

emsdk_manifest.json
test/test_activation.ps1
test/test_path_preservation.ps1

We use the native version of closure compiler these days so we don't need to install java on windows IIUC.
See https://github.com/emscripten-core/emscripten/pull/20919

Don't install java when installing windows sdk

---

.github/workflows/tag-release.yml

When triggered from Chromium CI, the credential is for the emscripten-bot account.

Update release tagging workflow to handle external triggering

---

.github/workflows/create-release.yml

This still requires a human to review, but one less button to click.

Enable auto-merge for bot-created PRs

---

bazel/emscripten_toolchain/BUILD.bazel
docker/Dockerfile
emsdk.py
scripts/update_bazel_workspace.py
scripts/update_node.py
test/test.bat
test/test.py

% `codespell`
```
./emsdk.py:1459: thier ==> their
./test/test.bat:1: equivilent ==> equivalent
./test/test.py:198: Specificlly ==> Specifically
./scripts/update_bazel_workspace.py:2: revisons ==> revisions
./scripts/update_node.py:11: direcotry ==> directory
./bazel/emscripten_toolchain/BUILD.bazel:57: implictly ==> implicitly
./docker/Dockerfile:87: terninal ==> terminal
```

Fix typos discovered by codespell

---

.flake8
bazel/emscripten_toolchain/link_wrapper.py
emsdk.py
scripts/create_release.py
scripts/get_emscripten_revision_info.py
scripts/get_release_info.py
scripts/update_python.py
scripts/zip.py
test/test.py

Related to
* #1497 
After re-reading the [flake8 configuration docs](https://flake8.pycqa.org/en/latest/user/configuration.html), I remembered that using `flake8 --extend-ignore` instead of `--ignore` greatly reduces the number of active lint rules.

Python lint: Use flake8 --extend-ignore instead of --ignore

---

.github/workflows/create-release.yml
scripts/create_release.py

This changes the CLI syntax for create_relase.py to be more compatible with
argparse, but we don't run it often manually anyway.

Allow overriding version number in create_release.py

---

bazel/emscripten_toolchain/BUILD.bazel
bazel/emscripten_toolchain/default_config
bazel/emscripten_toolchain/toolchain.bzl

The current way to derive the binary path relies on a specific name for the nodejs repository. This blocks migrating to bzlmod, as bzlmod prefixes repository directories with the module name that created them. By asking bazel for the path instead we always get the correct path, so we can work with both bzlmod and WORKSPACE based dependencies at the same time.
The repository @nodejs, used in the build label, refers to nodejs for the host platform and is generated by the following macro (wasn't too obvious to me):
https://github.com/bazel-contrib/rules_nodejs/blob/d19d695275c5fd0d5224ddc7826d9f7f4b8186df/nodejs/repositories.bzl#L452
This is some work towards solving #1509.

Bazel: Pass nodejs binary path as an environment variable.

---

bazel/toolchains.bzl

local=True marks a repository rule to unconditionally re-execute anytime bazel re-evaluates the workspace (almost every invocation) It works well for processes that execute in <10ms, not large ones like the embuilder cache generation.
I have tested this locally and it seems to work fine, but I'll be honest that I don't understand the nuances of repository rules that well, nor do I know much of anything about emscripten or the circumstances in which the cache ought to be rebuilt.
I checked the `external/@emscripten_cache.marker` file that Bazel uses to store the cache key for if it needs to re-evaluate, and changing any of the options passed into register_emscripten_toolchains resulted in the cache key changing, and it correctly resulted in the cache being regenerated.
The big question I …

Do not mark cache generation as local

---

emsdk.py

See https://chromium.googlesource.com/emscripten-releases/+/2ee2f60605a7774b4e194c235e372c29973038ab

Remove closure compile hack when running `npm ci`

---

emsdk.py

These seems to be some issue with building gtest on ubuntu/focal.  Looks like maybe the libstdc++ is too old for it.

Don't build binaryen tests

---

emsdk
emsdk.bat

The `-0` and `-1` suffixes here are not part of the install path which only based on the `id` and `version` of the tool. e.g:
```
{
"id": "python",
"version": "3.9.2",
"bitness": 64,
"arch": "x86_64",
"windows_url": "python-3.9.2-1-embed-amd64+pywin32.zip",
"activated_cfg": "PYTHON='%installation_dir%/python.exe'",
"activated_env": "EMSDK_PYTHON=%installation_dir%/python.exe"
},
```
Here we have a `-1` in the archive name, but that is not included in the version which is used to construct the install path.
Fixes: #1570

Fix python search path in emsdk launcher scripts

---

.circleci/config.yml

This was accidentally removed in #1183

[CI] Re-enable python2 flake8 checking

---

emsdk_manifest.json
scripts/update_node.py

This PR updates Node.js from earlier 22.16.0 to newer 24.7.0.
Remove armv7l and 32-bit Windows, https://github.com/nodejs/nodejs.org/issues/8123

Add Node.js 24.7.0 support.

---

.circleci/config.yml
test/test.bat

`C:\Python312\python.exe` is already in the path by default.
We no longer need to set this special path or environment variable.  In fact this code was doing nothing since it was adding the end of the PATH so the system python was already coming first.

Use default python in PATH for circleci windows bot. NFC
